# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Administrator/Desktop/miniRV_1/miniRV_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/ip/inst_mem/test.coe
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/ALU.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/Branch.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/Control.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/DMem.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/IMem.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/ImmGen.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/NextPC.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/PC.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/RegFile.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/display.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/divider.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/miniRV.v
  C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/new/top_display.v
}
read_ip -quiet C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/ip/data_mem/data_mem.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/ip/data_mem/data_mem_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/ip/cpuclk/cpuclk.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/ip/cpuclk/cpuclk_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/ip/cpuclk/cpuclk.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/ip/cpuclk/cpuclk_ooc.xdc]

read_ip -quiet C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/ip/inst_mem/inst_mem.xci
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/sources_1/ip/inst_mem/inst_mem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/miniRV_1/miniRV_1.srcs/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_display -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_display.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_display_utilization_synth.rpt -pb top_display_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
